import fetch from "node-fetch";
import fs from "fs";
const animeTitles = [
  "girlfriend girlfriend",
  "girls und panzer",
  "golden time",
  "gto",
  "gurren lagann",
  "haikyuu",
  "hells paradise",
  "higehiro",
  "high school mercenary",
  "highspeed etoile",
  "hokkaido gals are adorable",
  "honey lemon soda",
  "hope your happy lemon",
  "horimiya",
  "i have a crush at work",
  "I’ll become a villainess who goals down in history",
  "inazuma eleven",
  "initial d",
  "in/spectre",
  "i want to eat your pancreas",
  "jisan baasan wakagaeru",
  "jojo’s bizarre adventures",
  "joshiraku",
  "jujutsu kaisen",
  "childhood friends complex",
  "kaguya sama love is war",
  "kaiju n°8",
  "kakegurui",
  "katainaka no ossan",
  "kill la kill",
  "kimi no todoke",
  "kimi wa maid sama",
  "kindergarten wars",
  "kowloon generic romance",
  "kuroko no basket",
  "le fruit de la grisaia",
  "left hand layup",
  "kusuriya no hitorigoto",
  "liar liar",
  "link click",
  "love after world domination",
  "love agency",
  "love is like a cocktail",
  "lycoris recoil",
  "maoyuu maou yuusha",
  "mashle",
  "mirai nikki",
  "mission yozakura family",
  "mob psycho",
  "moi le maitre des interdit",
  "tensei shitara slime datta ken",
  "monogatari series",
  "monster",
  "mushoku tensei",
  "my deer friend nokotan",
  "my dress up darling",
  "my first girlfriend is a gal",
  "my happy marriage",
  "my hero academia",
  "my love story with yamada kun to lvl 99",
  "my step sister is my ex",
  "my wife has no emotion",
  "nisekoi",
  "noble new world adventure",
  "no game no life",
  "one piece",
  "one punch man",
  "orange",
  "oregairu",
  "oshi no ko",
  "our dating story, the inexperienced me",
  "parasite",
  "partners 2.0",
  "pleure pour cette fleur",
  "possibly the greatest alchemist",
  "pseudo harem",
  "reincarnated as the 7th prince",
  "re:monster",
  "rent a girlfriend",
  "re:zero",
  "ron kamonoashi",
  "roshidere",
  "run with the wind",
  "ruri rocks",
  "sailor moon",
  "saint cecilia and pastor lawrence",
  "sakamoto days",
  "sakamoto desu ga",
  "science i fell in love",
  "senpai wa otokonoko",
  "seraph of the end",
  "the seven deadly sins",
  "7th time loop",
  "shikimori isn't just cute",
  "so im a spider so what",
  "solo leveling",
  "soul eater",
  "spice and wolf",
  "spy x family",
  "stardust telepath",
  "super cube",
  "sword art online",
  "kijin gentochou",
  "the 100 girlfriends",
  "the angel next door",
  "the daily life of the immortal king",
  "the danger in my heart",
  "the dreaming man is a realist",
  "the eminence in shadow",
  "the extra’s academy survival guide",
  "the girl downstairs",
  "the girl who forgot her glasses",
  "the misfit of the demon king academy",
  "the pet girl of sakurasou",
  "the quintessential quintuplets",
  "the rising of the shield hero",
  "the world finest assassin",
  "tokyo mew mew",
  "tomodachi game",
  "tonikaku kawaii",
  "toradora",
  "umibe no etranger",
  "undead unluck",
  "vermeil in gold",
  "vinland saga",
  "violet evergarden",
  "whisper me a love song",
  "wind breaker",
  "wonder egg priority",
  "wotakoi",
  "your lie in april",
  "you name",
  "zombieland saga"
]
;

async function getAnimeIds(titles) {
  for (const title of titles) {
    try {
      const query = encodeURIComponent(title);
      const res = await fetch(`https://api.jikan.moe/v4/anime?q=${query}&limit=1`);
      const data = await res.json();
      const anime = data?.data?.[0];
      if (anime) {
        console.log(`  { id: ${anime.mal_id}, type: "anime" }, // ${anime.title}`);
      } else {
        console.warn(`❌ Aucun résultat pour: ${title}`);
      }
      await new Promise(r => setTimeout(r, 400)); // pour ne pas surcharger l’API
    } catch (err) {
      console.error(`Erreur pour ${title}:`, err);
    }
  }
}

getAnimeIds(animeTitles);
